import type {
  Candidate,
  Job,
  ExperienceTask,
  CompetencyStatusRow,
  CourseHealthRecord,
  DistrictMetric,
} from '../types'

export const DEMO_CANDIDATE: Candidate = {
  id: 1,
  name: 'Riddhi Naskari',
  email: 'riddhi.demo@swamarga.local',
  target_role: 'Cloud Support Associate',
  location: 'Pune, Maharashtra',
  resume_text: 'MCA graduate from Pune University. Strong foundation in Linux system administration, bash scripting, and cloud infrastructure on AWS. Completed course in cloud fundamentals.',
}

export const DEMO_COMPETENCY_MATRIX: CompetencyStatusRow[] = [
  {
    skill: 'Linux',
    marketDemand: 'High',
    skillStatus: 'Demonstrated',
    evidenceStatus: 'Verified',
    score: 84,
    evidenceType: 'Practical Assessment (Service Failure Diagnosis)',
    recommendedAction: 'Maintained · Verified in Competency Passport',
    actionUrl: '/candidate/passport',
  },
  {
    skill: 'Troubleshooting',
    marketDemand: 'High',
    skillStatus: 'Demonstrated',
    evidenceStatus: 'Verified',
    score: 88,
    evidenceType: 'Practical Assessment (Cloud Troubleshooting Scenario)',
    recommendedAction: 'Maintained · Verified in Competency Passport',
    actionUrl: '/candidate/passport',
  },
  {
    skill: 'AWS',
    marketDemand: 'High',
    skillStatus: 'Demonstrated',
    evidenceStatus: 'Evidence Gap',
    score: null,
    evidenceType: 'Self-Reported / Course Completion Certificate',
    recommendedAction: 'Execute Cloud Routing Task on Experience Bridge',
    actionUrl: '/candidate/experience-bridge/2',
  },
  {
    skill: 'Networking',
    marketDemand: 'High',
    skillStatus: 'Skill Gap',
    evidenceStatus: 'Not Demonstrated',
    score: null,
    evidenceType: 'None on record',
    recommendedAction: 'Enroll in Networking Practical Training Module',
    actionUrl: '/candidate/training',
  },
  {
    skill: 'Docker',
    marketDemand: 'Medium',
    skillStatus: 'Skill Gap',
    evidenceStatus: 'Not Demonstrated',
    score: null,
    evidenceType: 'None on record',
    recommendedAction: 'Complete Container Fundamentals Coursework',
    actionUrl: '/candidate/training',
  },
]

export const DEMO_EXPERIENCE_TASKS: ExperienceTask[] = [
  {
    id: 1,
    title: 'Diagnose a Linux Service Failure (systemd)',
    role: 'Cloud Support Associate',
    skill: 'Linux',
    difficulty: 'Intermediate',
    estimated_minutes: 45,
    why_it_matters: 'Cloud support roles require rapid isolation of crashed daemon processes under production Linux instances.',
    description: 'An Nginx web service on an EC2-compatible Linux instance has stopped responding following a configuration patch. Inspect journalctl logs, locate syntax errors in the server configuration, test using nginx -t, restore the daemon, and submit diagnostic log evidence.',
    instructions: [
      'Inspect service status via systemctl status nginx and note active exit code.',
      'Query system logs using journalctl -u nginx -n 50 --no-pager to isolate the syntax failure in /etc/nginx/conf.d.',
      'Correct the misplaced semicolon on line 42 and validate configuration syntax with nginx -t.',
      'Reload the daemon and verify port 80/443 listener binding using ss -tulpn.',
      'Summarize your diagnostic findings and attach CLI command history.',
    ],
    expected_evidence: [
      'Exact journalctl log extract pinpointing the failure',
      'CLI command history showing verification with nginx -t',
      'Active running status output from systemctl',
    ],
    rubric: [
      { criterion: 'Diagnostic Isolation Methodology', weight: '30%' },
      { criterion: 'Command Accuracy & Efficiency', weight: '30%' },
      { criterion: 'Root Cause Documentation', weight: '40%' },
    ],
  },
  {
    id: 2,
    title: 'Troubleshoot a Cloud VPC Route Table Connectivity Failure',
    role: 'Cloud Support Associate',
    skill: 'AWS',
    difficulty: 'Intermediate',
    estimated_minutes: 60,
    why_it_matters: 'Validates practical AWS networking troubleshooting beyond theoretical certification questions.',
    description: 'An application server inside a private subnet cannot reach an S3 Gateway Endpoint. Verify security groups, network ACLs, and route table destinations. Reconfigure the route entry to point to the correct VPC prefix list.',
    instructions: [
      'Review the subnet route table association and check destination CIDR blocks.',
      'Check Security Group egress rules for HTTPS traffic (port 443).',
      'Diagnose the missing VPC Gateway Endpoint route entry for com.amazonaws.ap-south-1.s3.',
      'Add the route entry to the private subnet route table.',
      'Demonstrate endpoint reachability and output curl -I https://s3.ap-south-1.amazonaws.com response.',
    ],
    expected_evidence: [
      'Route table configuration JSON before and after modification',
      'Egress connectivity verification log',
      'Technical explanation of the Gateway Endpoint routing requirement',
    ],
    rubric: [
      { criterion: 'Route Table Analysis', weight: '35%' },
      { criterion: 'VPC Security Group Rules', weight: '25%' },
      { criterion: 'Verification & Artifact Quality', weight: '40%' },
    ],
  },
  {
    id: 3,
    title: 'Investigate a Docker Container CrashLoopBackOff Scenario',
    role: 'Cloud Support Associate',
    skill: 'Docker',
    difficulty: 'Advanced',
    estimated_minutes: 50,
    why_it_matters: 'Containerized microservices dominate modern cloud infrastructure deployments.',
    description: 'A containerized Node.js API service keeps exiting immediately upon startup. Inspect docker logs and container exit codes, fix missing environment variable definitions, rebuild the image, and verify healthy container status.',
    instructions: [
      'Execute docker inspect and docker logs to determine container exit code (Exit 1).',
      'Identify unhandled rejection caused by missing DATABASE_URL environment parameter.',
      'Pass correct runtime variables via .env or CLI flag and re-run container.',
      'Confirm container health status through docker ps and container healthcheck logs.',
    ],
    expected_evidence: [
      'Initial crash log capture',
      'Corrected docker run or docker-compose snippet',
      'Active container uptime proof',
    ],
    rubric: [
      { criterion: 'Log Inspection & Root Cause', weight: '40%' },
      { criterion: 'Container Runtime Configuration', weight: '30%' },
      { criterion: 'Healthy State Proof', weight: '30%' },
    ],
  },
]

export const DEMO_JOBS: Job[] = [
  {
    id: 1,
    title: 'Cloud Support Associate',
    company: 'TechCloud Solutions Pvt Ltd',
    location: 'Pune (Hinjawadi)',
    description: 'Provide Tier-1 and Tier-2 technical support for cloud-hosted client infrastructures. Troubleshoot Linux instances, configure AWS routing, and diagnose container incidents.',
    skills: ['Linux', 'AWS', 'Networking', 'Troubleshooting', 'Docker'],
    matched_skills: ['Linux', 'Troubleshooting'],
    missing_skills: ['Networking', 'Docker'],
    missing_evidence: ['AWS (Certificate on file, practical proof required)'],
    match_rationale: 'Strong practical match on core Linux diagnosis and troubleshooting. Resolving AWS Experience Bridge task will elevate profile to full verified status.',
  },
  {
    id: 2,
    title: 'Junior Cloud Operations Associate',
    company: 'CloudNova Systems',
    location: 'Pune (Magarpatta)',
    description: 'Support production cloud deployments, manage monitoring dashboards, and perform basic networking triage on Linux virtual servers.',
    skills: ['AWS', 'Linux', 'Networking', 'Troubleshooting'],
    matched_skills: ['Linux', 'Troubleshooting'],
    missing_skills: ['Networking'],
    missing_evidence: ['AWS'],
    match_rationale: 'Candidate meets 2 of 4 required competencies with high practical verification scores (Linux: 84, Troubleshooting: 88).',
  },
  {
    id: 3,
    title: 'Cloud Infrastructure Trainee',
    company: 'DataGrid Systems India',
    location: 'Pune (Viman Nagar)',
    description: 'Entry-level cloud role. Candidates with verified hands-on Linux administration and incident troubleshooting are given immediate interview preference.',
    skills: ['Linux', 'Troubleshooting', 'Docker'],
    matched_skills: ['Linux', 'Troubleshooting'],
    missing_skills: ['Docker'],
    missing_evidence: [],
    match_rationale: 'Candidate has verified practical proof for the two primary qualification pillars. Employer accepts on-the-job training for Docker.',
  },
  {
    id: 4,
    title: 'Technical Support Engineer',
    company: 'NextGen Technologies',
    location: 'Mumbai (Airoli)',
    description: 'Diagnose network outages, inspect server logs, and collaborate with Level-3 DevOps teams on cloud infrastructure stability.',
    skills: ['Linux', 'Networking', 'Troubleshooting', 'AWS'],
    matched_skills: ['Linux', 'Troubleshooting'],
    missing_skills: ['Networking'],
    missing_evidence: ['AWS'],
    match_rationale: 'High compatibility with incident triage workflow. Candidate is invited to submit Experience Bridge proof for AWS.',
  },
]

export const DEMO_COURSE_HEALTH: CourseHealthRecord[] = [
  {
    id: 1,
    courseName: 'Cloud Infrastructure & Linux Systems (6 Months)',
    sector: 'IT-ITeS',
    enrolledStudents: 120,
    placementRate: 78,
    marketAlignment: 'Optimal',
    topMissingSkill: 'VPC Gateway Routing',
    action: 'Maintain curriculum · Integrate Experience Bridge tasks',
  },
  {
    id: 2,
    courseName: 'Diploma in Computer Hardware & Networking',
    sector: 'Electronics & IT',
    enrolledStudents: 85,
    placementRate: 46,
    marketAlignment: 'Review Required',
    topMissingSkill: 'Container Fundamentals (Docker)',
    action: 'Update legacy networking curriculum with cloud routing modules',
  },
  {
    id: 3,
    courseName: 'Traditional Server Administration (On-Premises)',
    sector: 'IT Infrastructure',
    enrolledStudents: 60,
    placementRate: 28,
    marketAlignment: 'Declining',
    topMissingSkill: 'Public Cloud Services (AWS / Azure)',
    action: 'Phase out on-prem physical lab modules; migrate to virtual cloud lab environments',
  },
]

export const DEMO_DISTRICTS: DistrictMetric[] = [
  {
    district: 'Pune',
    targetRoleDemand: 2850,
    activeTrainees: 1600,
    certifiedTrainers: 42,
    capacityDeficit: 1250,
    mismatchLevel: 'High',
  },
  {
    district: 'Mumbai Suburban',
    targetRoleDemand: 3400,
    activeTrainees: 2200,
    certifiedTrainers: 58,
    capacityDeficit: 1200,
    mismatchLevel: 'High',
  },
  {
    district: 'Nagpur',
    targetRoleDemand: 820,
    activeTrainees: 650,
    certifiedTrainers: 19,
    capacityDeficit: 170,
    mismatchLevel: 'Moderate',
  },
  {
    district: 'Nashik',
    targetRoleDemand: 640,
    activeTrainees: 580,
    certifiedTrainers: 15,
    capacityDeficit: 60,
    mismatchLevel: 'Balanced',
  },
  {
    district: 'Chhatrapati Sambhajinagar',
    targetRoleDemand: 520,
    activeTrainees: 380,
    certifiedTrainers: 12,
    capacityDeficit: 140,
    mismatchLevel: 'Moderate',
  },
]


